### ISSUE TITLE
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found : '% Processor Time'

### ISSUE THREAD

**Issue by will-stone** [flakshack/pyPerfmon#1]
Using the counter in your screenshot:

```
processor_time=\Processor(_Total)\% Processor Time
```

I get the following error:

Traceback (most recent call last):
    File "<string>", line 41, in <module>
    File "C:\Users\vinsco\test\build\pyperfmon\out00-PYZ.pyz\ConfigParser", line 655, in items
    File "C:\Users\vinsco\test\build\pyperfmon\out00-PYZ.pyz\ConfigParser", line 691, in _interpolate
    File "C:\Users\vinsco\test\build\pyperfmon\out00-PYZ.pyz\ConfigParser", line 732, in _interpolate_some
    ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found
: '% Processor Time'

**Comment by flakshack** [comment]
The percent symbol has a special function when used in strings in Python, so it should be escaped.  Use "%%" instead of "%" and it should work fine.

**Comment by will-stone** [comment]
Hi Flakshack, thanks for that. Just getting a response of:

```
{"error": ""}
```

Which is strange as your test (for memory) works just fine. I know this is now off topic, but any ideas?
Thanks.
