### ISSUE TITLE
Return error when fetching Processor User time

### ISSUE THREAD

**Issue by evgygor** [flakshack/pyPerfmon#2]
Hi,

The default test configuration works fine.

I tried to add the  additional counter: 'cpu0 = \Processor(0)\% User Time'

Exception on start of service:
C:\Users\Administrator\Downloads\pyPerfmon-master>pyperfmon.exe
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "C:\Users\vinsco\test\build\pyperfmon\out00-PYZ.pyz\ConfigParser", line 655, in items
  File "C:\Users\vinsco\test\build\pyperfmon\out00-PYZ.pyz\ConfigParser", line 691, in _interpolate
  File "C:\Users\vinsco\test\build\pyperfmon\out00-PYZ.pyz\ConfigParser", line 732, in _interpolate_some
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '% User Time'
C:\Users\Administrator\Downloads\pyPerfmon-master>

So i added % according to exception to INI file:

'cpu0 = \Processor(0)\%% User Time'

Service started as well, but response always is {"error": ""}

Thanks

**Comment by whoyax** [comment]
faced with the same problem

**Comment by flakshack** [comment]
Issue fixed in this [commit](https://github.com/flakshack/pyPerfmon/commit/903b8a1d26e81c8b462672b791048125e17a7175).  You will still have to include 2 percent symbols.
